### ISSUE TITLE
Implement Data Structures and Algorithms

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#1]
### **Steps to contribute -**

1. Open a new issue stating the algorithm/datastructure you want to implement.
2. Create a new PR and reference the issue in that PR.
3. Wait for the PR to be merged 🎉.

**Comment by NEENA-XAVIER** [comment]
I would like to add stack implementation using array in c !

**Comment by Ambareen09** [comment]
I would like to add Josephus Problem code in c++.

**Comment by psymbio** [comment]
@div-bargali can I add stacks, queues, linked list implementations?

**Comment by div-bargali** [comment]
To maintain a proper directory management 📂 please add the file inside a directory in following structure:
<Language>/<Algorithm | Data Structure>/<your file or folder>

**Comment by div-bargali** [comment]
> can I add stacks, queues, linked list implementations?
@psymbio Sure go ahead. Make sure they aren't already implemented and maintain a proper director.

**Comment by Ashish7129** [comment]
Hi @div-bargali ,

Can I add searching algorithms like linear or binary ??

**Comment by RahulRS246** [comment]
i would like to add queue using linked list in java

**Comment by jleahwolff** [comment]
Could I add Merge Sort for Python?

**Comment by aditimaurya** [comment]
I'd like to add sorting algorithm on python ( shell sort, bubble sort, selection sort, insertion sort, merge sort)
I'll check before adding them if they are already present or not. Kindly assign me this 🙂

**Comment by prajnapuranik** [comment]
Hey, can I add Bubblesort algorithm implementation in Java?

**Comment by NirmalKumarJoshi** [comment]
Hey @div-bargali I want to add Binary and Linear Search in C++. Can I proceed?

**Comment by div-bargali** [comment]
@NirmalKumarJoshi Sure.

**Comment by div-bargali** [comment]
Please create new issues for different languages. 😃

**Comment by vaishnavirshah** [comment]
Hi @div-bargali I want to add BST implementation in C++. Can i proceed?

**Comment by div-bargali** [comment]
@vaishnavirshah Sure 👍 , create a new issue and reference the issue in your PR.

**Comment by nirajmalpani** [comment]
I would like to add stack implementation in python

**Comment by iamvs-2002** [comment]
I would like to add more data structure implementations like Linked Lists, Queues, Heaps and Trees in C

**Comment by div-bargali** [comment]
@nirajmalpani @iamvs-2002 Make a new issue please. And reference that issue in your PR.

**Comment by nirajmalpani** [comment]
done @div-bargali

**Comment by nirajmalpani** [comment]
Can I contribute more like on some sorting algorithms in python?

**Comment by div-bargali** [comment]
@NirmalKumarJoshi Sure, create a new issue, make sure the algoritms aren't already implemented.

**Comment by kokilgupta** [comment]
Can I add selection sort and fractional knapsack?

**Comment by RamneekKaur983** [comment]
I want to add KMP Pattern Searching Algorithm in Java

**Comment by SusnatoPrime007** [comment]
I want to do stack using Java

**Comment by Anjalikamath** [comment]
Can I add 
1. Heapsort Implementation using C++
2. Binary Search on rotated array in C++
3. 3sum implementation in C++
4. Construct Binary Tree from inorder and preorder traversal in C++
5. Subset sum problem using DP

**Comment by Anjalikamath** [comment]
Hi @div-bargali 
Can I add :
1. Heapsort Implementation using C++
2. Binary Search on rotated array in C++
3. 3sum implementation in C++
4. Construct Binary Tree from inorder and preorder traversal in C++
5. Subset sum problem using DP

**Comment by div-bargali** [comment]
@Anjalikamath Sure. Open a new issue. If you will be making separate PRs make separate issues to track them.

**Comment by Anjalikamath** [comment]
@div-bargali  Heapsort in C++ is already implemented. Can I instead add : Morris Traversal Inorder and Preorder ?
