### ISSUE TITLE
Queue usings Stacks

### ISSUE THREAD

**Issue by sjatin-cse** [div-bargali/Data-Structures-and-Algorithms#100]
I want to add implementation of queue using 2 stacks in C.

**Comment by sayan2044** [comment]
I want to add implementation of queue using stack in C.

**Comment by div-bargali** [comment]
Assigned to @sjatin-cse based on issue creation.

**Comment by BhargaviChada** [comment]
Can I take this in Java?

**Comment by sayan2044** [comment]
can i do the same in python?

**Comment by div-bargali** [comment]
@BhargaviChada @sayan2044  Of course, make sure it's not already implemented and open a new issue. 👍
