### ISSUE TITLE
Fibonacci Series using Java

### ISSUE THREAD

**Issue by SusnatoPrime007** [div-bargali/Data-Structures-and-Algorithms#108]
I would like to do the fibonacci series in Java.Please assign me to this.

**Comment by ram2939** [comment]
Solved #123

**Comment by johan7004** [comment]
i would also like to work in this 
can you assign me on this  please ?

**Comment by PODU** [comment]
Has this been fixed?
If not I would like to work on this.

**Comment by SusnatoPrime007** [comment]
I am submitting my pr and makin a folder in java regarding my fibonacci program,please accept it
