### ISSUE TITLE
Maintain a proper directory structure.

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#11]
Make necessary changes to maintain a proper directory folder. Required directory structure should look like: <br>
`<Language>/<Algorithms>/<Algorithm Paradigm>/<. . .>`
`<Language>/<Data Structures>/<Data Structure name>/<. . .>` 

Make necessary changes in readme file to indicate the above mentioned requirement before creating a new pull request!

**Comment by GGn0** [comment]
Hi!
Can I work on it?

**Comment by JigarJoshi04** [comment]
I'm also ready to work. Assign it to any one of us

**Comment by div-bargali** [comment]
Assigned to @GGn0 . Make sure you add the requirements as a note at the end of readme file.

**Comment by div-bargali** [comment]
Fixed in #36

**Comment by div-bargali** [comment]
@JigarJoshi04 Would you like to work on it?

**Comment by coder-dev-geek** [comment]
@div-bargali Please assign it to me!

**Comment by div-bargali** [comment]
Fixed in #54
