### ISSUE TITLE
Subset Sum (DP) | C++

### ISSUE THREAD

**Issue by Anjalikamath** [div-bargali/Data-Structures-and-Algorithms#114]
### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

**Comment by Rsr0** [comment]
hii @div-bargali  can u assign it to me?

**Comment by div-bargali** [comment]
Assigned to @Anjalikamath based on issue creation.

**Comment by Rsr0** [comment]
ok sir.
