### ISSUE TITLE
Binary Tree from Inorder and Preorder Traversals | C++

### ISSUE THREAD

**Issue by Anjalikamath** [div-bargali/Data-Structures-and-Algorithms#115]
### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

**Comment by mrunalvilas** [comment]
hey can i work on this issue

**Comment by div-bargali** [comment]
@mrunalvilas I am sorry, I would have to assign it to @Anjalikamath based on issue creation, unless she's okay with you contributing to this issue.

**Comment by mrunalvilas** [comment]
@Anjalikamath I really didn't know about this, the one who creates issue, PR is allowed to made by that person only, will u be fine if My PR is considered?

**Comment by Anjalikamath** [comment]
@mrunalvilas I don't mind :)

**Comment by div-bargali** [comment]
Assined to @mrunalvilas
