### ISSUE TITLE
Quick Sort | Java

### ISSUE THREAD

**Issue by shevya06** [div-bargali/Data-Structures-and-Algorithms#118]
## **`Title`** - Quick Sort

**what will change** - adding code for java implementation of quick sort

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- 
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by shevya06** [comment]
I would like to contribute this

**Comment by abhimanyu-bitsgoa** [comment]
Hi @shevya06! Can I contribute to this?

**Comment by lucy-ctrl** [comment]
Hi, can I contribute to this? :) Thanks.

**Comment by Cuncis** [comment]
Can I contribute to this?

**Comment by div-bargali** [comment]
Assigned to @shevya06 based on issue creation.
