### ISSUE TITLE
Swap nodes in a linked list without swapping data | C

### ISSUE THREAD

**Issue by prajjwal-24** [div-bargali/Data-Structures-and-Algorithms#129]
Swap nodes in a linked list without swapping data 
in C

Basic problem of linked list, should be added for better understanding

### Type of Issue -
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C

Please assign this to me

**Comment by RajdeepDey010** [comment]
I want to add ,how to check for self loops in a linkedlist in C.
plss assign me this!
