### ISSUE TITLE
Lucky Number | Java

### ISSUE THREAD

**Issue by SusnatoPrime007** [div-bargali/Data-Structures-and-Algorithms#134]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] C
- [x] Go
- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SusnatoPrime007** [comment]
I am adding my pr

**Comment by div-bargali** [comment]
Assigned to @SusnatoPrime007 .

**Comment by SusnatoPrime007** [comment]
I have submitted two pr requests,one is quick sort which I got to know now that it is already assigned to someone else,another is lucky number which is assigned to me,kindly accept the latter one.
