### ISSUE TITLE
Doubly Linked List | Java

### ISSUE THREAD

**Issue by SusnatoPrime007** [div-bargali/Data-Structures-and-Algorithms#136]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] Go
- [x] C
- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SusnatoPrime007** [comment]
Please assign me to this.

**Comment by SusnatoPrime007** [comment]
Shall I make a separate folder for it or can I do it in LinkedList folder?

**Comment by div-bargali** [comment]
@SusnatoPrime007  It should be in LinkedList folder

**Comment by SusnatoPrime007** [comment]
Okay
