### ISSUE TITLE
Maintainers for the Repo.

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#145]
This repo is getting too big for one guy to maintain.
 If you have worked as a collaborator before or contributed to this repo and are interested to help maintain it. 🤔 

Join our [Discord Server](https://discord.gg/2qgQM7b) ✉️

**Comment by Satyajeet-code** [comment]
Great✌️✌️

**Comment by Satyajeet-code** [comment]
Great✌️✌️
