### ISSUE TITLE
Sieve of Eratosthenes-Finding Prime Numbers in a range | Python

### ISSUE THREAD

**Issue by jai2dev** [div-bargali/Data-Structures-and-Algorithms#161]
## **`Sieve of Eratosthenes`** -

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

**Comment by RiyaM16** [comment]
I'd like to contribute. Please assign it to me.
Thanks!

**Comment by jai2dev** [comment]
hey @div-bargali where i should add this in the algorithm folder; should i make a new floder inside algorithm folder or just add the file inside the algorithm folder

**Comment by div-bargali** [comment]
@jai2dev Sieve is based on Maths, so add a new folder by name Mathematical Algorithms.

**Comment by jai2dev** [comment]
okay

**Comment by saurabh-172** [comment]
@div-bargali 
I'm new to hactoberfest and open source contributions and I wanted to ask that can we contribute to issues which are already assigned to someone like in this case or it will be violation of conditions, confirming to be sure I'm not doing something wrong as it's new for me.

**Comment by div-bargali** [comment]
> @div-bargali
> I'm new to hactoberfest and open source contributions and I wanted to ask that can we contribute to issues which are already assigned to someone like in this case or it will be violation of conditions, confirming to be sure I'm not doing something wrong as it's new for me.

Hi, so answering your question, no it's not a violation of any terms, it's just that generally the person opening the issue get's assigned, but more than 1 person can be assigned the same issue. But since not a lot of algos or data strcutures are implemented yet, I'd suggest you open a new issue on something that's not yet implemented. 😃

**Comment by saurabh-172** [comment]
thanks for clearing my doubt now that I know how to contribute by opening an issue but I don't know how to open an issue like should I open the issue in my repository or yours or the forked one which I would be forking from yours? can you Please guide so that I don't mess it up?

**Comment by saurabh-172** [comment]
so now the issue has closed that means I can't contribute right but at least can you guide me by answering the above question? 😢

**Comment by jai2dev** [comment]
> thanks for clearing my doubt now that I know how to contribute by opening an issue but I don't know how to open an issue like should I open the issue in my repository or yours or the forked one which I would be forking from yours? can you Please guide so that I don't mess it up?
> Also, I'm willing to learn DSA while practicing it in python like this was one of the reasons I choose to do this issue so also can you suggest me a beginner-friendly DSA which I can implement in here. In the data structure, I know arrays and in algorithms, I know binary search and bubble sort, need to learn more.

First learn how to contribute in open source, search on google or youtube. It wont take that much time
