### ISSUE TITLE
Queue, Stack, DoublyLinkedList | C#

### ISSUE THREAD

**Issue by Danotsonof** [div-bargali/Data-Structures-and-Algorithms#172]
## **`Implementation of Queue, Stack and DoublyLinkedList in C#`**

**what will change**

### Type of Issue

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C#

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Danotsonof** [comment]
Kindly assign this to me.

**Comment by div-bargali** [comment]
@Danotsonof Since C# is not yet implemented previously, please make a new folder in root named: `C#/Data-Structures/<DS name>/<ds implementation>`
