### ISSUE TITLE
AVL Tree | Python

### ISSUE THREAD

**Issue by b72u68** [div-bargali/Data-Structures-and-Algorithms#176]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by kajal-puri** [comment]
Hi, can you assign this to me? I want to work on this issue.

**Comment by b72u68** [comment]
Sorry, I'm working on this issue right now
