### ISSUE TITLE
Arrays| c++

### ISSUE THREAD

**Issue by siddhamsj** [div-bargali/Data-Structures-and-Algorithms#202]
## **`To place positive element at even and negative at odd position in an array.`** -

**Problem solving** -

### Type of issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language: 

Please add/delete options that are not relevant.

- [x] C++

please assogn this tome.

**Comment by OMEGAeNcore** [comment]
Please assign me this.

**Comment by div-bargali** [comment]
This issue is open.

**Comment by OMEGAeNcore** [comment]
I would like to be assigned

**Comment by stuti-ui** [comment]
@div-bargali can you assign this to me.

**Comment by div-bargali** [comment]
Assigned to @OMEGAeNcore
