### ISSUE TITLE
Implementation of disjoint set (C++)

### ISSUE THREAD

**Issue by cp1307** [div-bargali/Data-Structures-and-Algorithms#210]
Implementation of disjoint set (C++)

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by karthick191999** [comment]
can u assign this to me @jai2dev  @div-bargali  ?

**Comment by jai2dev** [comment]
@karthick191999 it is already assigned to someone else.. so come up with something else

**Comment by karthick191999** [comment]
as in i dont understand ?
