### ISSUE TITLE
Euler's totient Function

### ISSUE THREAD

**Issue by cp1307** [div-bargali/Data-Structures-and-Algorithms#211]
Euler's totient Function

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by div-bargali** [comment]
@cp1307 Create a new folder in `C++/Algorithms` and name it `Mathematical Algoritms` and add your files there.
