### ISSUE TITLE
Sieve of eratosthenes

### ISSUE THREAD

**Issue by cp1307** [div-bargali/Data-Structures-and-Algorithms#212]
Sieve of eratosthenes

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by jai2dev** [comment]
remember to make a folder mathematical algorithms under algorithms and then put that inside it

**Comment by 0ne0rZer0** [comment]
Hey I would like to work on this issue, Can you assign it to me?

**Comment by ajayjha5899** [comment]
Code ready on my forked repo. Please assign this issue to me so that I can open a valid PR.
