### ISSUE TITLE
Djikstras using a MinHeap with O(1) put() and O(log(n)) decrement() | golang

### ISSUE THREAD

**Issue by suramrit** [div-bargali/Data-Structures-and-Algorithms#232]
## **`Topic`** - Implementation of Djikstras Algo for Min Cost Path

**what will change** - Djikstras Algo for Min Cost Path to be added to graph algorithms for golang

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] Go

I have an implementation ready for a PR, can you please assign this issue to me

**Comment by jai2dev** [comment]
@suramrit make a new folder for this lang and add it accordingly
