### ISSUE TITLE
Operations on Array | C

### ISSUE THREAD

**Issue by Gaurisha21** [div-bargali/Data-Structures-and-Algorithms#236]
## **`Operations on Array`** -

**what will change** - The  code will perform Operations like Traversing, Insertion, Sort, Search and Deletion

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language 

Please add/delete options that are not relevant.

- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Gaurisha21** [comment]
Please assign this issue to me.

**Comment by NandiniMundra-8** [comment]
Can you assign this to me and and Can I use c++ language to perform this task ?
thank you.

**Comment by div-bargali** [comment]
@NandiniMundra-8 Open a new issue. Make sure it's not already there before opening a new issue.

**Comment by div-bargali** [comment]
Duplicate issue. Closed. 🛑
