### ISSUE TITLE
Priority queue | c++

### ISSUE THREAD

**Issue by SharmilaSrinivasa** [div-bargali/Data-Structures-and-Algorithms#237]
## **`Priority queue in c++`** -

**what will change** -
Priority queue

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by jai2dev** [comment]
Change the issue name to priority queue with the respecting lang

**Comment by SharmilaSrinivasa** [comment]
I changed it.

**Comment by jai2dev** [comment]
aare the title of the issue

**Comment by jai2dev** [comment]
i have assigned it to you, go for it, just put it in right folder

**Comment by SharmilaSrinivasa** [comment]
So, now I just need to fork, make change then pull.Am I right?

**Comment by jai2dev** [comment]
are you new to open source ?

**Comment by jai2dev** [comment]
> So, now I just need to fork, make change then pull.Am I right?

yeah

**Comment by NandiniMundra-8** [comment]
hey I am nandini,can you assign this task to me and can I perform this using C language ?
Thank you.
