### ISSUE TITLE
Longest Common Subsequence using DP | Python3

### ISSUE THREAD

**Issue by p-nath** [div-bargali/Data-Structures-and-Algorithms#246]
## **`Longest Common Subsequence`** -
Thinking of adding code to find the Longest Common Subsequence using Dynamic Programming
### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by meetpandya4715** [comment]
I would like to contribute here to solve this issue. Please assign me this issue so that I can proceed to make PR.

**Comment by Satyajit-Codys** [comment]
I would also like to contribute.
