### ISSUE TITLE
ShellSort | Python

### ISSUE THREAD

**Issue by MostDeadDeveloper** [div-bargali/Data-Structures-and-Algorithms#249]
## **`Applying the ShellSort Algorithm in Python`** -

**what will change** - 
I will be adding a new python file containing the implementation of ShellSort.

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by MostDeadDeveloper** [comment]
Assign this to me, I will be working on it

**Comment by NandiniMundra-8** [comment]
hey @div-bargali ,I would like to perform it, can you assign this to me?
can we use CPP/C language also to perform it ?
thank you .

**Comment by SaloniK17** [comment]
hii,can you please assign to me for c?
Thank you

**Comment by jai2dev** [comment]
open up a new issue regarding this guys

**Comment by rishika-singh49** [comment]
I would like to work on this ....
can you please assign to me for c?
