### ISSUE TITLE
Bfs using queue| C++

### ISSUE THREAD

**Issue by Nitishg1223** [div-bargali/Data-Structures-and-Algorithms#253]
## **`Bfs using queue`** -

**what will change** -it will add a program of breadth first searc using queue

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by geekaditi** [comment]
Hi, I would like to take this up. Please assign it to me.
