### ISSUE TITLE
Dfs using stack | C++

### ISSUE THREAD

**Issue by Nitishg1223** [div-bargali/Data-Structures-and-Algorithms#254]
## **`Title`** -  DFS using stack

**what will change** - It will add a new program of depth first search using stack

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by Bhavya-Tripathi** [comment]
I would like to contribute. Can you assign this issue to me?
