### ISSUE TITLE
Binary Search Tree | C

### ISSUE THREAD

**Issue by Harshalszz** [div-bargali/Data-Structures-and-Algorithms#262]
## **`Binary Search Tree`** -

**what will change** - I will add a file in C for binary search tree implementation. Including all traversals like inorder, preorder and postorder.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ankitsri98** [comment]
Sir Please Assign Me This Doubt.
thank you.
