### ISSUE TITLE
Max Profit with k transactions (DP)  | C++

### ISSUE THREAD

**Issue by logeshb** [div-bargali/Data-Structures-and-Algorithms#264]
## **`Max Profit with k transactions (DP)`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by logeshb** [comment]
I like to work on this issue

**Comment by loge1998** [comment]
I will raise PR in this account. I mistakenly logged in from other account. Extremely sorry for this

**Comment by ByteCode-Test** [comment]
please assign this to me i can solve this as soon as possible
thank you
