### ISSUE TITLE
Program for nth Catalan Number | c++

### ISSUE THREAD

**Issue by cp1307** [div-bargali/Data-Structures-and-Algorithms#265]
## **`Title`** - Program for nth Catalan Number

The code to find the nth catalan number

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by KoushikSahu** [comment]
I want to work on this issue. Please assign it to me.
