### ISSUE TITLE
Deleting a node in link list| C++

### ISSUE THREAD

**Issue by siddhamsj** [div-bargali/Data-Structures-and-Algorithms#274]
## **`Deleting a node** -

**Adding a new code** -
**Improvising the code**

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improvising the code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
- [ ] Add more details regarding the issue.

**Comment by siddhamsj** [comment]
Changed the topic to deleting a node in linklist.

**Comment by sid-1207** [comment]
I would like to solve it in C++(C)
Please assign it to me

**Comment by rishika-singh49** [comment]
can i do it in c ?
