### ISSUE TITLE
KMP Algorithm | Pattern-Searching | Python

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#278]
## **`KMP Algorithm | Pattern-Searching | Python`** -

**what will change** -
Implementation of KMP algorithm.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
Anyone who would like to work on it?

**Comment by astha01** [comment]
I would love to contribute!

**Comment by jai2dev** [comment]
> I would love to contribute!

Alright comrade, you are assigned

**Comment by kakashi215** [comment]
I was looking for some algorithms to contribute as well.
@astha01 are you working on it?
Could i work along?

**Comment by datasorceress** [comment]
I would like to contribute!

**Comment by div-bargali** [comment]
Assigned to @datasorceress
