### ISSUE TITLE
Algorithm or Data Structure name | Language

### ISSUE THREAD

**Issue by kvv1618** [div-bargali/Data-Structures-and-Algorithms#281]
## **`Title`** - New algorithms belonging to greedy and mathematical concepts 

**what will change** -  Addition of new code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
@dhairya-parikh Sure, open a new issue.
