### ISSUE TITLE
Queue using stacks | C++

### ISSUE THREAD

**Issue by siddhamsj** [div-bargali/Data-Structures-and-Algorithms#285]
## **`Queue using stacks`** -

**Problem solving** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by therupdeep** [comment]
@siddhamsj i would like to work on this!

**Comment by DebarshiChanda** [comment]
@siddhamsj I would like to implement this!

**Comment by jai2dev** [comment]
> I would like to work on this using C++.....

open a new issue dude
