### ISSUE TITLE
Addition of more data structure implementations

### ISSUE THREAD

**Issue by iamvs-2002** [div-bargali/Data-Structures-and-Algorithms#29]
I am interested to contribute to this repository by adding more implementations for datastructures like Linked Lists, Queues, Trees and Heaps in C language.

**Comment by div-bargali** [comment]
Assigned to @iamvs-2002

**Comment by iamvs-2002** [comment]
Thanks a lot for assigning this task to me.

**Comment by iamvs-2002** [comment]
I forked the repository and did the implementations. Could please check my contributions.

**Comment by div-bargali** [comment]
Create a pull request first.

**Comment by iamvs-2002** [comment]
So, there is no need of forking this repository?

**Comment by iamvs-2002** [comment]
Done!

**Comment by div-bargali** [comment]
Solved in #32
