### ISSUE TITLE
Insertion and Quick sort | C

### ISSUE THREAD

**Issue by sarthak-21** [div-bargali/Data-Structures-and-Algorithms#290]
## **`Insertion and Quick sort`** -

**what will change** -

### Type of Issue -

- [x] Adding New Code
- [x] Adding a _Readme.md_

### Programming Language

Please add/delete options that are not relevant.

- [x] C
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by sarthak-21** [comment]
@div-bargali I would like to do it in C. Assign this to me.

**Comment by Suraj1199** [comment]
@div-bargali I would request you to assign the issue to me for other languages. (Python or C++)

**Comment by DrashtiKoladiya** [comment]
@div-bargali I would like to do it in C++, python, and C. I request you to assign this issue to me.

**Comment by Aayush-Bhatt** [comment]
I am working on this and will submit PR in a while.

**Comment by div-bargali** [comment]
@Suraj1199 @DrashtiKoladiya Open new issues.

**Comment by Suraj1199** [comment]
@div-bargali didn’t get you
