### ISSUE TITLE
Graph and its representation | Python

### ISSUE THREAD

**Issue by durgeshahire07** [div-bargali/Data-Structures-and-Algorithms#297]
## **`Graph and its representation`** -

**A new program on Graph data structure in Python** -

### Type of Issue - #296 

Please add/delete options that are not relevant.

- [✓] Adding New Code

### Python

Please add/delete options that are not relevant.

- [✓] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by durgeshahire07** [comment]
hello @div-bargali ,
i went through the repository and found that graph is being already added in python. 
so, can i add graph concept in java ?

**Comment by ap-darknight** [comment]
Going to add graph concepts based on DFS and BFS, should I?
Thanks in advance!!
