### ISSUE TITLE
Insertion Sort | C

### ISSUE THREAD

**Issue by CosmicGirl42** [div-bargali/Data-Structures-and-Algorithms#304]
## **`Insertion Sort`** -

**what will change** - Create a file with an implementation of insertion sort in C.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by CosmicGirl42** [comment]
Can I be assigned to this issue?

**Comment by maddysan0407** [comment]
@div-bargali is your project open for further improvements/changes ,can I contribute towards your project?

**Comment by vikramadityasinghs** [comment]
Can I be assigned to this issue?

**Comment by vikramadityasinghs** [comment]
@div-bargali @CosmicGirl42 I want to contribute to this project? can this be assigned to me?

**Comment by sharathkumar106** [comment]
I am willing to contribute to this issue. I kindly request you to assign me for this. 😄

**Comment by rishikumar-p** [comment]
Hey @div-bargali  I want to contribute to this. could you assign this to me?

**Comment by harshitalashkari** [comment]
Can I work on this ?

**Comment by SudhanshuBlaze** [comment]
Please assign it to me.

**Comment by bhavinisehgal18** [comment]
please assign this to me

**Comment by 19isha98** [comment]
Hey I am interested in doing it could you please assign it to me.

**Comment by iamrk09** [comment]
Hey, I want to make a contribution for hacktoberfest. Please assign it to me.

**Comment by Divyansh833** [comment]
Hey @CosmicGirl42, I am Searching for my very first Hacktoberfest and this looks very perfect for me.
Could you please assign it to me.
Thanks in advance :) !!
