### ISSUE TITLE
Disjoint Union Set | Java

### ISSUE THREAD

**Issue by sonu7089** [div-bargali/Data-Structures-and-Algorithms#317]
## **`Disjoint Union Set`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by rathovarun** [comment]
@sonu7089 Can you assign this issue to me? thanks!

**Comment by ahmeddrawy** [comment]
I can implement  count number of connected components using DSU implemented by @sonu7089  and can extend the class to help solving various DSU problems
