### ISSUE TITLE
Prim's Algorithm | Java

### ISSUE THREAD

**Issue by sharathkumar106** [div-bargali/Data-Structures-and-Algorithms#318]
## **`Prim's Algorithm`** -

**A new file to be added demonstrating the Prim's Algorithm** -

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by sabrajsab** [comment]
please assign this to me
