### ISSUE TITLE
Heap (Kth Largest Element in a Stream )| C++

### ISSUE THREAD

**Issue by sidrakshe28** [div-bargali/Data-Structures-and-Algorithms#321]
## **`Title`** -  Kth Largest Element in a Stream 

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by sidrakshe28** [comment]
Please assign me this issue. Would like to try this problem.

**Comment by sabrajsab** [comment]
i have done similar problem already. please assign this to me
