### ISSUE TITLE
0-1 Knapsack in python

### ISSUE THREAD

**Issue by PrasanthChettri** [div-bargali/Data-Structures-and-Algorithms#326]
## **`0-1 Knapsack`** -

**what will change** -
0-1 Knapsack Algorithm will be added which is a famous dynamic programming algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by PrasanthChettri** [comment]
Can I be assigned to this issue ?

**Comment by div-bargali** [comment]
Up for grabs!

**Comment by Bereim** [comment]
I'd like to be assigned to this issue.
