### ISSUE TITLE
Arrays | C++

### ISSUE THREAD

**Issue by atish-90** [div-bargali/Data-Structures-and-Algorithms#329]
## **`Move all the negative elements of arrays to the left`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by atish-90** [comment]
Please assign this issue to me

**Comment by sabrajsab** [comment]
Please assign this issue to me

**Comment by Sindhu-321** [comment]
Can i get this assigned? Thanks.

**Comment by Pysche666** [comment]
Please assign this issue to me. Thanks!
