### ISSUE TITLE
Linked list in python

### ISSUE THREAD

**Issue by UsamaKashif** [div-bargali/Data-Structures-and-Algorithms#33]
I will add Linked List in Python

**Comment by div-bargali** [comment]
Assigned to @UsamaKashif

**Comment by Poobalan1210** [comment]
I will add doubly linked list in Python.Can you assign me.

**Comment by div-bargali** [comment]
@Poobalan1210 Sure create a new issue.

**Comment by div-bargali** [comment]
Solved #37
