### ISSUE TITLE
Floyd's Cycle-Finding Algorithm | C++

### ISSUE THREAD

**Issue by atish-90** [div-bargali/Data-Structures-and-Algorithms#331]
## **`Detect a loop in LinkedList`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by atish-90** [comment]
Please assign this issue to me

**Comment by sabrajsab** [comment]
Please assign this issue to me

**Comment by aritra-sarkar99** [comment]
@atish-90  I would be glad to contribute, could you assign this issue to me ?

**Comment by ahmeddrawy** [comment]
If still available or need code review please let me know
