### ISSUE TITLE
backtracking algorithm for sudoko in c++

### ISSUE THREAD

**Issue by HeisenBug-07** [div-bargali/Data-Structures-and-Algorithms#341]
### Type of Issue - adding new file.

- [x] Adding New Code

### Programming Language
- [x] C++

**Comment by SynneK1337** [comment]
I would like to work on that one.

**Comment by ambuj2000** [comment]
please assign me this issue

**Comment by sidrakshe28** [comment]
Can you assign this issue to me .Would like to work on this problem.

**Comment by SynneK1337** [comment]
Please assign me to this issue as I finished working on this one.

**Comment by haider000** [comment]
Please assign this issue to me. I would like to work on this as I made the project of sudoku solver just a month ago.
