### ISSUE TITLE
Algorithm or Data Structure name | C++

### ISSUE THREAD

**Issue by Pysche666** [div-bargali/Data-Structures-and-Algorithms#344]
## **`Adding Data Structure type`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
@Pysche666 Add more details and specifics on what you want to implement/contribute to!
