### ISSUE TITLE
Backtracking | Python

### ISSUE THREAD

**Issue by Bhavartha** [div-bargali/Data-Structures-and-Algorithms#354]
## **`N-Queens Problem`** -

**Repo will contain solution of N-Queens problem by backtracking method(python)** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Bhavartha** [comment]
Please assign this issue to me. Thanks!

**Comment by leli-1** [comment]
Can i solve this if it is available? Can you assign it to me ?
