### ISSUE TITLE
Implementation of Doubly Linked List | C++

### ISSUE THREAD

**Issue by Pysche666** [div-bargali/Data-Structures-and-Algorithms#356]
## **`Implementation of Doubly Linked Lis`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Pysche666** [comment]
Please assign this issue to me.

**Comment by imshahnawazdevil** [comment]
could you assign this task to me?

**Comment by ambuj2000** [comment]
Please assign me this issue...

**Comment by Anurajeev** [comment]
Please assign me to this issue

**Comment by Anurajeev** [comment]
could you please assign this to me
