### ISSUE TITLE
Breadth First Search and Depth First Search | C++

### ISSUE THREAD

**Issue by tharani247** [div-bargali/Data-Structures-and-Algorithms#360]
**Breadth First Search and Depth First Search**-

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

 - [] Python
 - [x]  C++
- [] Java
- [] C
- [] Go
- [] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by keshavga1209** [comment]
I would like to add this code in C++. Kindly assign it to me.
Thank you!

**Comment by Riyana6** [comment]
Please assign me to this.

**Comment by tharani247** [comment]
I opened this issue regarding the missing algorithm, please assign me this

**Comment by ambuj2000** [comment]
Can you assign me this issue
