### ISSUE TITLE
Tower of Hanoi Problem (Recursion) | C++

### ISSUE THREAD

**Issue by joharikushagra** [div-bargali/Data-Structures-and-Algorithms#361]
## **`printing total steps required to transfer n discs from source to destination tower** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by joharikushagra** [comment]
I would like to work on this @div-bargali

**Comment by Riyana6** [comment]
I like to work on this

**Comment by ambuj2000** [comment]
Can you let me work on this @div-bargali

**Comment by liamm91** [comment]
Can you assign me this issue?
