### ISSUE TITLE
Comb Sort | Python

### ISSUE THREAD

**Issue by UdeshAthukorala** [div-bargali/Data-Structures-and-Algorithms#363]
## **`Title`** - Comb Sort Algorithm

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by UdeshAthukorala** [comment]
@div-bargali Hey, Can you please assign this issue to me?

**Comment by liamm91** [comment]
Can you assign me this issue? I can do it in either C++ or Python

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.
