### ISSUE TITLE
Deletion in Circular Linked List | C++

### ISSUE THREAD

**Issue by muskanlalit18** [div-bargali/Data-Structures-and-Algorithms#365]
## **Deleting a Node in Circular Linked List** -

**what will change** -

A new C++ script will be added for deletion of a node in a circular linked list

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by muskanlalit18** [comment]
Please assign this issue to me.

**Comment by ambuj2000** [comment]
Please assign me this issue

**Comment by adityagread** [comment]
please assign me this issue

**Comment by Shreya2221** [comment]
I would like to delete a node in circular linked list using C++. Please assign this issue to me.

**Comment by liamm91** [comment]
Can I contribute?

**Comment by vidhya001** [comment]
Could you please assign this to me

**Comment by Anurajeev** [comment]
Could you assign this to me

**Comment by anujjain5699** [comment]
plz assign this issue to me

**Comment by SAKSHI2569** [comment]
can you please assign me this issue?
