### ISSUE TITLE
0 1 2 Sort Technique | C++

### ISSUE THREAD

**Issue by muskanlalit18** [div-bargali/Data-Structures-and-Algorithms#367]
## **0 1 Sort Technique** -

**what will change** -

A new C++ script will be added for 0 1 Sort Technique

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by muskanlalit18** [comment]
Please assign this issue to me.

**Comment by ambuj2000** [comment]
please assign me this issue

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.
