### ISSUE TITLE
Articulation Points and Bridges in Graph | C++

### ISSUE THREAD

**Issue by ErR0rpj** [div-bargali/Data-Structures-and-Algorithms#368]
## **`Articulation Point and Bridges`** -

**what will change** - Code to find Articulation Point and Bridges in graph

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Error404m** [comment]
hey @ErR0rpj , I wanna work pl.
