### ISSUE TITLE
tree | java

### ISSUE THREAD

**Issue by dhruvbatra810** [div-bargali/Data-Structures-and-Algorithms#370]
## **`tree creation and traversal`** -

**what will change** -
 code for creation of tree  and it's traversal (using implementation of stacks and queue) 

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding, happy hacktoberfest

**Comment by ambuj2000** [comment]
Please assign me this issue

**Comment by dhruvbatra810** [comment]
please assign this  to me

**Comment by asaadxheikh** [comment]
please assign this to me

**Comment by dhruvbatra810** [comment]
i am done with the code , please assign
