### ISSUE TITLE
Graph Traversal | C

### ISSUE THREAD

**Issue by Sashi445** [div-bargali/Data-Structures-and-Algorithms#374]
## **`Title`** - Adding Breadth First Search and Depth First Search 

**what will change** -

Add BFS implementation using C langauge

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Ace117MC** [comment]
can you assign this to me

**Comment by techbayindia** [comment]
Assign Me!

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.

**Comment by nishantkumar1308** [comment]
can u assign this to me??please!!!

**Comment by shubhamsolank24** [comment]
i can work on this can you assign me this

**Comment by div-bargali** [comment]
Assigned to @shubhamsolank24

**Comment by SauravBaba** [comment]
@div-bargali  please assign to me

**Comment by sharmishtha2401** [comment]
assign this to me please
