### ISSUE TITLE
Backtracking | C++

### ISSUE THREAD

**Issue by SnehhaPadmanabhan** [div-bargali/Data-Structures-and-Algorithms#375]
## **`NQueens Problem using backtracking in C++`** -

**Adding code to implement N Queens problem as a classic back tracking example** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SnehhaPadmanabhan** [comment]
Please assign this issue to me

**Comment by liamm91** [comment]
Can you assign this issue to me?

**Comment by sidrakshe28** [comment]
Can you assign me this issue. I would like to take this up.
