### ISSUE TITLE
Graph algorithm | C++

### ISSUE THREAD

**Issue by SnehhaPadmanabhan** [div-bargali/Data-Structures-and-Algorithms#376]
## **`Detecting cycle in a directed graph using DFS`** -

**Adding code for cycle detection in a graph C++** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SnehhaPadmanabhan** [comment]
Please assign this issue to me. Thanks!

**Comment by codeit-dotcom** [comment]
please assign this to me.
