### ISSUE TITLE
Array | C++

### ISSUE THREAD

**Issue by Error404m** [div-bargali/Data-Structures-and-Algorithms#377]
## **`Title` Move all zeroes to end of array** -

**what will change** - Adding code for moving all zeroes to end of array

### Type of Issue -

- [x] Adding New Code
-  Improving Code
-  Improving Documentation
-  Bug Fix

### Programming Language

-  Python
- [x] C++
-  Java
-  C
-  Go
-  Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Jeewantha95** [comment]
Please assign this issue to me. Thanks!

**Comment by Error404m** [comment]
pls assign me,

**Comment by Jeewantha95** [comment]
Oh sorry @Error404m
