### ISSUE TITLE
KMP - Pattern Searching Algorithm | C++

### ISSUE THREAD

**Issue by jmilan1** [div-bargali/Data-Structures-and-Algorithms#384]
Adding 4 Pattern Searching Algorithm in CPP

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

Happy Coding,

**Comment by jmilan1** [comment]
please assign this issue to me, I have already made the PRs for them by mistake

**Comment by div-bargali** [comment]
@jmilan1 In case that I have closed the PRs please make them again and mention the issue number. It's a must, as there's no other way to tell spam PRs from genuine ones.
