### ISSUE TITLE
Linear Search | C

### ISSUE THREAD

**Issue by pedrousp** [div-bargali/Data-Structures-and-Algorithms#386]
## Adding Linear Search Algorithm in C

It'll be added, in this case, linear search algorithm in C.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C

### Self Check 

- Ask for issue assignment before makin
g Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by maw1a** [comment]
I can work on this.

**Comment by SiddhantBobde** [comment]
Can I work on this issue?

**Comment by dhruvbatra810** [comment]
can i also work on this issue?

**Comment by pedrousp** [comment]
Give it to me, please.

**Comment by pedrousp** [comment]
Please, assign this to me.

**Comment by nishantkumar1308** [comment]
please assign this to me

**Comment by kakabisht** [comment]
HI, I could take care of this issue, let me know if it is up for grabs.
