### ISSUE TITLE
Implement Stack in Java || Data Structures

### ISSUE THREAD

**Issue by ug2454** [div-bargali/Data-Structures-and-Algorithms#39]
implement stack in java using array and linked List

**Comment by div-bargali** [comment]
@ug2454 Make sure the folder structure is as specified in [Contribution Guide](https://github.com/div-bargali/Data-Structures-and-Algorithms/blob/main/CONTRIBUTING.md)

**Comment by ug2454** [comment]
@div-bargali i have added. Is the directory structure acceptable?

**Comment by div-bargali** [comment]
Solved in #40
