### ISSUE TITLE
Tower Of Hanoi | C

### ISSUE THREAD

**Issue by Rudransh24** [div-bargali/Data-Structures-and-Algorithms#400]
## Tower Of Hanoi 

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Rudransh24** [comment]
Can I be assigned to this issue in C ?

**Comment by atharvakarnik** [comment]
Hey @div-bargali, I would like to contribute using Python, can you assign this to me?

**Comment by Suraj1199** [comment]
@div-bargali please assign me in C++

**Comment by sanchitgupta456** [comment]
Can i be assigned this ?
How do i get assigned ?

**Comment by IndrashisChatterjee** [comment]
Assign me please

**Comment by ChetanaL09** [comment]
Please assign this to me for Python
