### ISSUE TITLE
3-Way QuickSort (Dutch National Flag) | C

### ISSUE THREAD

**Issue by Rudransh24** [div-bargali/Data-Structures-and-Algorithms#402]
## 3-Way QuickSort (Dutch National Flag)

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Rudransh24** [comment]
Can I be assigned to this issue in C ?

**Comment by Hitesh18082001** [comment]
could you please assign this issue to me

**Comment by shubham14596** [comment]
Please assign this issue to me for java
