### ISSUE TITLE
Bitonic Sort | C++

### ISSUE THREAD

**Issue by Rudransh24** [div-bargali/Data-Structures-and-Algorithms#405]
## Bitonic Sort

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Rudransh24** [comment]
Can I be assigned to this issue in C++ ?

**Comment by kakabisht** [comment]
Hi, I can implement this in a couple of hours, let me know if it is up for grabs.

**Comment by surya-x** [comment]
Please assign it to me, i'll be doing it in Python and C.
