### ISSUE TITLE
Addition of 2x2 Matrix in C

### ISSUE THREAD

**Issue by Gaurisha21** [div-bargali/Data-Structures-and-Algorithms#406]
## **Addition of 2x2 Matrix in C** -

**It will add two 2x2 Matrix in C language** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Siddharth009** [comment]
can i be assigned to this?

**Comment by Gaurisha21** [comment]
I have raised the issue so that it can be assigned to me.

**Comment by adilsp5075** [comment]
i would like to contribute can u assign me

**Comment by harshulab** [comment]
Can i please be assigned to this issue?

**Comment by olivia26** [comment]
can i be assigned? I'm new to this Git. I want to contribute.

**Comment by Anurajeev** [comment]
i like to contribute...can you assign to me

**Comment by neha07kumari** [comment]
Please assign me this issue. @Gaurisha21  @div-bargali
