### ISSUE TITLE
Rabinkarp - Pattern Searching Algorithm | C++

### ISSUE THREAD

**Issue by jmilan1** [div-bargali/Data-Structures-and-Algorithms#407]
## **`Title`** - Rabinkarp - Pattern Searching Algorithm | C++

**what will change** - Adding Rabin karp Pattern Searching algorithm

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by jmilan1** [comment]
Please assign this to me

**Comment by atish-90** [comment]
I already made the issue on this and also created the pull request.

**Comment by atish-90** [comment]
check issue #359

**Comment by atish-90** [comment]
Also, you can make a pull request for an issue only if you are assigned to it.

**Comment by div-bargali** [comment]
@atish-90 Thanks for pointing it out.
