### ISSUE TITLE
Kruskal’s Minimum Spanning Tree Algorithm | C++

### ISSUE THREAD

**Issue by arpit7714** [div-bargali/Data-Structures-and-Algorithms#410]
## **`Title`** - Kruskal’s Minimum Spanning Tree Algorithm

**what will change** - Adding Kruskal.cpp

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by arpit7714** [comment]
Please assign this to me

**Comment by dev-shubham1** [comment]
Hey everyone, 
I am Shubham Ghule. 
I would really like to take this issue if not assigned ?

**Comment by amintai** [comment]
@dev-shubham1 @div-bargali    can i work on the same? as i've learned Kruskal's Algorithm.

**Comment by rahul975337** [comment]
can i work on this?
