### ISSUE TITLE
sorting algorithms in python

### ISSUE THREAD

**Issue by nirajmalpani** [div-bargali/Data-Structures-and-Algorithms#42]

**Comment by DvnOshin** [comment]
I would like to add Insertion sort in python.

**Comment by div-bargali** [comment]
@nirajmalpani @DvnOshin Some algorithms are already implemented, sync your repos with the main repo. Refer Contribution Guide to check how.

**Comment by sayan2044** [comment]
I have added radix sort using python. please check

**Comment by div-bargali** [comment]
Resolved in #99
