### ISSUE TITLE
Algorithm or Data Structure name | LanguageData-Structures-and-Algorithms/C++/Algorithms/Backtracking/ Backtracking algorithm not present

### ISSUE THREAD

**Issue by Ms3105** [div-bargali/Data-Structures-and-Algorithms#434]
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] C
- [x] Go
- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Error404m** [comment]
Hey, Can I work on this please ?

**Comment by neha07kumari** [comment]
Please assign me this . I want to add new problems from data structure- linked list. Can I? @Ms3105  @div-bargali

**Comment by div-bargali** [comment]
It's not clear what is the topic you want to implement. Please open a new issue, with some details.
