### ISSUE TITLE
Reverse a stack without using extra space in O(n) | C++

### ISSUE THREAD

**Issue by devmrfitz** [div-bargali/Data-Structures-and-Algorithms#435]
## **`Title`** - Reverse a stack without using extra space in O(n)

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by dev-shubham1** [comment]
I would really like to take up this issue. Could you please assign it to me ?

**Comment by devmrfitz** [comment]
I've already requested this as I've created it
