### ISSUE TITLE
Hacktoberfest Labels are not named correctly

### ISSUE THREAD

**Issue by VenkatVuddagiri** [div-bargali/Data-Structures-and-Algorithms#438]
All the labels with hacktoberfest should actually be "hactoberfest-accepted" and not just "hactoberfest". Please correct them from now on

**Comment by div-bargali** [comment]
@VenkatVuddagiri Well the labels are correct. `hacktoberfest-accepted` label is only for PRs, and if the PR is merged then you don't need the label on your PR, as it will considered a valid PR since it's merged.
