### ISSUE TITLE
Linear And Binary Search Algorithm | C#

### ISSUE THREAD

**Issue by AtalKhandelwal** [div-bargali/Data-Structures-and-Algorithms#440]
## **`Title`** -
Linear And Binary Search Algorithm

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] C#
- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by AtalKhandelwal** [comment]
@div-bargali Please assign this isssue to me. I can do it in C#.

**Comment by Pratyushraj2121** [comment]
@div-bargali Can you assing this to me? I can do this using C language!

**Comment by Jeewantha95** [comment]
@div-bargali Please assign this issue to me. I can do it in C#.

**Comment by neha07kumari** [comment]
Please assign me this issue . I want to go for it using C. @AtalKhandelwal  @div-bargali
