### ISSUE TITLE
Prims Algorithm for Finding Minimum Spanning Tree | C++

### ISSUE THREAD

**Issue by ritik-sys** [div-bargali/Data-Structures-and-Algorithms#445]
## **`Prims Algorithm`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ritik-sys** [comment]
Can i work on this?

**Comment by arpit7714** [comment]
Issue already present #409
