### ISSUE TITLE
Stack Using Linked List | C++

### ISSUE THREAD

**Issue by ritik-sys** [div-bargali/Data-Structures-and-Algorithms#446]
## **`Stack Using Linked List`** -

**what will change** -
Adding new code for implementation of stack datastructure by use of Linked List
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ritik-sys** [comment]
Please Assign this to me

**Comment by snehaa1989** [comment]
I can code stack data structure using an array as well as linked list, please assign this to me

**Comment by anujjain5699** [comment]
plz assign this issue to me

**Comment by neha07kumari** [comment]
Please assign me this issue. Can I go for it using C or C++? @ritik-sys  @div-bargali
