### ISSUE TITLE
LinkedList | C++

### ISSUE THREAD

**Issue by gitarthasarma** [div-bargali/Data-Structures-and-Algorithms#447]
## **`Reverse two linked lists iteratively and recursively`** -

**what will change** -
Add c++ implementation of how to reverse two linked lists both iteratively and recursively and compare the complexity in both cases
### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by gitarthasarma** [comment]
Assign it to me

**Comment by snehaa1989** [comment]
I would like to code this problem, I would be grateful if you assign it to me!!

**Comment by YashJain2** [comment]
I want to contribute on this project under hacktoberfest please assign me in c++.
will work on both single and double linked list to reverse recursively and iteratively.
