### ISSUE TITLE
Kosaraju's Algorithm to find number of strongly connected components | C++

### ISSUE THREAD

**Issue by SnehhaPadmanabhan** [div-bargali/Data-Structures-and-Algorithms#453]
## **`Kosaraju's algorithm`** -

**Adding code for the algorithm in C++** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SnehhaPadmanabhan** [comment]
Please assign this issue to me. Thanks!

**Comment by ChetanaL09** [comment]
Please assign this to me for Python.
