### ISSUE TITLE
Algorithms/Greedy - Weighted Job Scheduling  | C++

### ISSUE THREAD

**Issue by rishab1128** [div-bargali/Data-Structures-and-Algorithms#456]
## **`Weighted Job Scheduling using Greedy Approach and Binary Search `** -

**what will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by rishab1128** [comment]
I have already completed the code with proper explanation in the comments, can you assign this issue to me!!!

**Comment by ritik-sys** [comment]
Please assign this to me
