### ISSUE TITLE
Counting Sort | c++

### ISSUE THREAD

**Issue by ritik-sys** [div-bargali/Data-Structures-and-Algorithms#458]
## **`Counting Sort`** -

**A file with code of counting sort** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ritik-sys** [comment]
Please assign this code to me

**Comment by Muskan33** [comment]
Please assign this to me

**Comment by sharmishtha2401** [comment]
please assign this to me if it is still open
