### ISSUE TITLE
Check whether a graph is connected or Not | C++

### ISSUE THREAD

**Issue by ritik-sys** [div-bargali/Data-Structures-and-Algorithms#459]
## **`Title`** -

**Code to check whether given graph is connected or not** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ritik-sys** [comment]
Please assign this to me

**Comment by Muskan33** [comment]
Please assign this to me.

**Comment by Sumanya312** [comment]
Please assign this to me
