### ISSUE TITLE
Dijkstra’s shortest path algorithm | C++

### ISSUE THREAD

**Issue by arpit7714** [div-bargali/Data-Structures-and-Algorithms#479]
## **`Title`** - Dijkstra’s shortest path algorithm

**what will change** - Adding Dijkstra’s Algorithm

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by arpit7714** [comment]
please assign it to me

**Comment by codeit-dotcom** [comment]
can you assign this to me?

**Comment by namankhurpia** [comment]
can i do it in Java, please assign it to me

**Comment by neha07kumari** [comment]
Please assign me this issue . I want to contribute it in C. Can I? @arpit7714  @div-bargali

**Comment by Levi-ackerman24** [comment]
assign it to me for c#

**Comment by demonslayer99** [comment]
assign it to me for c#

**Comment by surya-x** [comment]
Please assign to me, i'll be doing it in C and Python.

**Comment by anuj840** [comment]
please assign it to me
