### ISSUE TITLE
Word break problem | Backtracking | C++

### ISSUE THREAD

**Issue by SnehhaPadmanabhan** [div-bargali/Data-Structures-and-Algorithms#481]
## **`Word breaking problem`** - Given an string and a dictionary of words, find out if the input string can be broken into a space-separated sequence of one or more dictionary words

**what will change** - Adding code for word break problem using backtracking in C++ 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by SnehhaPadmanabhan** [comment]
Please assign this issue to me. Thanks!

**Comment by namankhurpia** [comment]
Please assign it to me in Java, I can do it
