### ISSUE TITLE
Z algorithm | C++

### ISSUE THREAD

**Issue by sahebsunny** [div-bargali/Data-Structures-and-Algorithms#503]
## **`Z algorithm`** -

**what will change** - Adding Z algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by sahebsunny** [comment]
I appreciate it if you could assign this issue to me. I love to work on it.
Thank you.

**Comment by sahebsunny** [comment]
@div-bargali 
Sir, I am new to open source.
When I submitted this issue I did not know this algorithm is already been submitted by someone else(Data-Structures-and-Algorithms/C++/Algorithms/Pattern-Searching).
Sir now what should I do, should I send my Pr with the implementation of Z_algorithm?
Thank you for your time.

**Comment by hemanth-kotagiri** [comment]
@sahebsunny I appreciate your interest in Open Source Contributions. But, we are not accepting new PRs of implementations which already exist. I would recommend you to implement any other Algorithm/Data Structure **in your own unique way** and raise a new PR. 
Also, make sure to follow the PR/Issue templates provided to you. 

Thanks!
