### ISSUE TITLE
A* search algorithm | C++

### ISSUE THREAD

**Issue by sahebsunny** [div-bargali/Data-Structures-and-Algorithms#504]
## **`A* search algorithm`** -

**what will change** - Adding A* search algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by sahebsunny** [comment]
I appreciate it if you could assign this issue to me. I love to work on it.
Thank you.

**Comment by 0Verlord-41** [comment]
Is it still open?

**Comment by 0Verlord-41** [comment]
I would really love to help.

**Comment by jai2dev** [comment]
@0Verlord-41 you can do it in any other language like python; make sure to open a different issue for it
