### ISSUE TITLE
Deletion From a Binary Search Tree | C++

### ISSUE THREAD

**Issue by ksinha5nov** [div-bargali/Data-Structures-and-Algorithms#512]
## **`Deleting an Element From a Binary Search Tree`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ksinha5nov** [comment]
Please assign this issue to me, Thank you.

**Comment by anujjain5699** [comment]
Please assign this issue to me

**Comment by Sumanya312** [comment]
Please assign this issue to me sir.
