### ISSUE TITLE
Data Structure - Nested_Linked_List  |  C

### ISSUE THREAD

**Issue by Soham182001** [div-bargali/Data-Structures-and-Algorithms#526]
## **`Title`**  Linked Of Linked List in C

**what will change** 

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Soham182001** [comment]
I have already completed the code can you please assign this issue to me.

**Comment by div-bargali** [comment]
Linked list is already implemented.

**Comment by Soham182001** [comment]
Its Nested Linked List and it is different from the simple linked list and we have to define two structures and we have to manage two addresses for the node.

**Comment by div-bargali** [comment]
Title wasn't clear before. You can work on this issue. 👍
