### ISSUE TITLE
 Analyze performance, translate readme files, comment and find typos | C++ or C

### ISSUE THREAD

**Issue by ji-sang-geun** [div-bargali/Data-Structures-and-Algorithms#531]
## **`Title`** -
Is it possible to analyze the performance, translate the Readme file, and comment on the file?
**what will change** -
I'm trying to perform a performance analysis of your code, but I've committed to asking if it's possible Also, can the Readme file in English be translated into Korean?
If the Readme file is translated into Korean, Koreans who are blocked by language barriers approach and contribute, and it was decided that it was easy, so I proposed it.
Finally, we want to check for typos in the code and add comments to unfinished comments. Is this possible?
I came up with a suggestion because it helps to make it easier to understand how the code works while writing comments, and you can also find typos.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++
- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
@ji-sang-geun Great issue. Will look forward for your PR 😃

**Comment by ji-sang-geun** [comment]
First, I am trying to translate the Code of conduct file and the Readme file. Can you choose whether to write Korean below the existing file or add Readme (korean) or Code of conduct (korean) files? First of all, translation is in progress. and then, Second, I will add comments to the algorithm folder and DS folder in the C++ folder. Later, I plan to analyze the performance of the files in the C++ folder. And when I finish C++, I plan to do translation and performance analysis of C language.

**Comment by ji-sang-geun** [comment]
> @ji-sang-geun Great issue. Will look forward for your PR 😃

First, I am trying to translate the Code of conduct file and the Readme file. Can you choose whether to write Korean below the existing file or add Readme (korean) or Code of conduct (korean) files? First of all, translation is in progress. and then, Second, I will add comments to the algorithm folder and DS folder in the C++ folder. Later, I plan to analyze the performance of the files in the C++ folder. And when I finish C++, I plan to do translation and performance analysis of C language.

**Comment by div-bargali** [comment]
> > @ji-sang-geun Great issue. Will look forward for your PR 😃
> 
> First, I am trying to translate the Code of conduct file and the Readme file. Can you choose whether to write Korean below the existing file or add Readme (korean) or Code of conduct (korean) files? First of all, translation is in progress. and then, Second, I will add comments to the algorithm folder and DS folder in the C++ folder. Later, I plan to analyze the performance of the files in the C++ folder. And when I finish C++, I plan to do translation and performance analysis of C language.

@ji-sang-geun Create a seperate readme-korean file and link it in the original readme.

**Comment by ji-sang-geun** [comment]
> > > @ji-sang-geun Great issue. Will look forward for your PR 😃
> > 
> > 
> > First, I am trying to translate the Code of conduct file and the Readme file. Can you choose whether to write Korean below the existing file or add Readme (korean) or Code of conduct (korean) files? First of all, translation is in progress. and then, Second, I will add comments to the algorithm folder and DS folder in the C++ folder. Later, I plan to analyze the performance of the files in the C++ folder. And when I finish C++, I plan to do translation and performance analysis of C language.
> 
> @ji-sang-geun Create a seperate readme-korean file and link it in the original readme.

First of all, we have almost finished the localization of the current readme file and code of conduct file. Also, while translating the code, we found that there were files with only the title written on the readme file of the algorithm part and the data structure part, and there were files with no contents. Can I fill it in...?
