### ISSUE TITLE
Circular Doubly Linked List | C

### ISSUE THREAD

**Issue by GabrielMotaBLima** [div-bargali/Data-Structures-and-Algorithms#561]
## **Circular Doubly Linked List** -

**what will change** - Adding Circular Doubly Linked List implementation using C language.

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by GabrielMotaBLima** [comment]
I appreciate it if you could assign this issue to me. I love to work on it.
Thank you.

**Comment by me-anant** [comment]
Please assign me this issue. I want to contribute.
Thanks!
