### ISSUE TITLE
Arrays | C++

### ISSUE THREAD

**Issue by adyabansal** [div-bargali/Data-Structures-and-Algorithms#571]
## **`Title`** - Sum of two Arrays

**what will change** - Add C++ implementation to add two different arrays

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by adyabansal** [comment]
Please assign this issue to me

**Comment by Anurag-ak99** [comment]
Hey @adyabansal please assign this issue to me if its still open.

**Comment by yoki-07** [comment]
I also want to contribute in this. Please assign me this. @Anurag-ak99

**Comment by ankita1618** [comment]
Please assign this issue to me
