### ISSUE TITLE
KMP Algorithm | C

### ISSUE THREAD

**Issue by drstrange11** [div-bargali/Data-Structures-and-Algorithms#588]
## **`Title`** -
Implementation of KMP Algorithm in C

**what will change** -
Adding an algorithm in C to codebase

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by drstrange11** [comment]
I will work on this. Hope its okay. If so, please assign it to me. @div-bargali

**Comment by aniket173000** [comment]
Hi can u assign this issue to me . I can implement this KMP algorithm in C and C++.
