### ISSUE TITLE
Modularise Swift Folder | Swift

### ISSUE THREAD

**Issue by stevhens** [div-bargali/Data-Structures-and-Algorithms#591]
## **`Modularise Swift Folder | Swift`**

**what will change**
- Swift Folder Contents (Files been lost after last PR, I will fix this)
- Readme docs (add Swift Language)

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Documentation
- [x] Modularize Folders

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by stevhens** [comment]
please assign this to me @div-bargali

**Comment by div-bargali** [comment]
@stevhens Readme has been updated, if you still want to add something more your're welcome.

**Comment by stevhens** [comment]
> @stevhens Readme has been updated, if you still want to add something more your're welcome.

Thank you for your great work, I have decided to do the folders modularisation only.

**Comment by stevhens** [comment]
Please review my Pull Request @div-bargali

Thank you
