### ISSUE TITLE
0-1 Knapsack Problem | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [div-bargali/Data-Structures-and-Algorithms#609]
## **`Title`** - 0-1 Knapsack Problem

**what will change** - The code has many bugs in it, for example assignments statements are used in place of conditional statements, and I will add proper documentation as well.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by ravjotkaamra** [comment]
I would like to work on this issue.

**Comment by snehaa1989** [comment]
Please assign this to me

**Comment by ravjotkaamra** [comment]
Please could you explain how is it duplicate, I haven't seen this issue raised by someone else and its also not fixed in the codebase as well.

**Comment by ravjotkaamra** [comment]
Sir, I think you have confused my issue with #326 which is actually based on python but my issue is based on C++
