### ISSUE TITLE
Graph Dfs Application

### ISSUE THREAD

**Issue by heri2468** [div-bargali/Data-Structures-and-Algorithms#622]
## **`Title`** - Count the number of islands in a grid

**what will change** - Code will be added

### Type of Issue - Application of DFS

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] C
- [] Go
- [] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by heri2468** [comment]
please assign me @div-bargali @jai2dev  for this task, this is an interview question and a nice application of DFS

**Comment by tyagi619** [comment]
Can I solve this issue?

**Comment by palakdavda22** [comment]
I would also like to add some variations in this question, please assign me this so that I can add more relevant material here.
