### ISSUE TITLE
Pigeonhole Sort | Python

### ISSUE THREAD

**Issue by peaky76** [div-bargali/Data-Structures-and-Algorithms#644]
## **Pigeonhole Sort for Python** -

**Adding an extra sorting algorithm for Python** -

### Type of Issue -

Please add/delete options that are not relevant.

- [] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Shr03mink** [comment]
I would like to work on this issue

**Comment by peaky76** [comment]
I added it as I would like to do it myself!

**Comment by datasorceress** [comment]
Can I do this one?
