### ISSUE TITLE
Merge Sort | Golang

### ISSUE THREAD

**Issue by RuteshRathod** [div-bargali/Data-Structures-and-Algorithms#645]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
Golang
Please add/delete options that are not relevant.
- [x] Go

Please assign me this issue. I will be implementing this problem in golang

**Comment by RuteshRathod** [comment]
Please assign me this issue. I will be implementing this problem in golang

**Comment by manavbhikadiya** [comment]
please assign it to me i have the solution of the merge sort among the sorting algorithms
