### ISSUE TITLE
Fractional Knapsack | C

### ISSUE THREAD

**Issue by swati-gwc** [div-bargali/Data-Structures-and-Algorithms#650]
## **`Fractional Knapsack` in C** -

**what will change** -

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by swati-gwc** [comment]
Please assign me this issue, I want to contribute to this.

**Comment by manavbhikadiya** [comment]
I have solution of this problem. please assign this to me and also i have good knowledge of data structure and algorithm.
