### ISSUE TITLE
Convert 24bit->8bit photo(with loss of colour)  | C++

### ISSUE THREAD

**Issue by Pandz18** [div-bargali/Data-Structures-and-Algorithms#652]
Hello , I was wondering if I could submit a c++ program on converting a 24bit photo into an 8 but unfortunately will lead to a loss of colour of the photo . 

Please add/delete options that are not relevant.

- [x] Adding New Code
- [  ] Improving Code
- [  ] Improving Documentation
- [  ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [. ] Python
- [x] C++
- [. ] Java
- [. ] C
- [. ] Go
- [. ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
@Pandz18 Sure go ahead, make sure it's inside the algorithms folder, and if it's a specific algorithm name it as a folder as well.

**Comment by Pandz18** [comment]
@div-bargali  , thank. you , will do
