### ISSUE TITLE
Quick sort | Python

### ISSUE THREAD

**Issue by shreyasd302** [div-bargali/Data-Structures-and-Algorithms#653]
## **`Title`** - Quick Sort

**what will change** - This will sort the given array using Quick sort algorithm.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by shreyasd302** [comment]
Can I do this please?

**Comment by datasorceress** [comment]
Can I do this one?
