### ISSUE TITLE
Greedy Algorithm for Egyptian Fraction | Python

### ISSUE THREAD

**Issue by Apoorva-Datir** [div-bargali/Data-Structures-and-Algorithms#654]
## **Egyptian Fraction`** -

**This will represent every positive fraction as as sum of unique unit fractions.** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Apoorva-Datir** [comment]
can i work on it please?

**Comment by datasorceress** [comment]
Can I work on this?
