### ISSUE TITLE
Pigeonhole Sort | C++

### ISSUE THREAD

**Issue by sahebsunny** [div-bargali/Data-Structures-and-Algorithms#656]
## **`Pigeonhole Sort`** -

**what will change** - A file with code of Pigeonhole Sort.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by snehaa1989** [comment]
please assign this to me, and review my PR

**Comment by verma-pulkit** [comment]
I would like to work on this in cpp.

**Comment by divitagulati** [comment]
Hey there,
I would like to work on it. Can you please assign this to me?

**Comment by namrata18s** [comment]
Could you assign me for java/python?

**Comment by namrata18s** [comment]
Could you assign me for C# language?
