### ISSUE TITLE
Bubble sort to sort an array in descending order

### ISSUE THREAD

**Issue by VarunSharma117** [div-bargali/Data-Structures-and-Algorithms#677]
## **`Title`** -

To add **Bubble sort** to sort an array in **descending order** in java
This algorithm isn't implemented yet. Please, assign it to me.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by div-bargali** [comment]
I don't see any reason why this issue is needed. All it needs is changing the comparison operator to sort in descending order.

#### CLOSED
