### ISSUE TITLE
Priority Queue | Python

### ISSUE THREAD

**Issue by Dilip-Jain** [div-bargali/Data-Structures-and-Algorithms#681]
## **`Title`** - Adding Priority Queue using Python

**what will change** - Priority Queue is a special type of data structure in which items can be inserted or deleted based on the priority. Priority Queue will be added in the data structures, implemented on python.

### Type of Issue -Priority Queue missing.

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

Please assign this to me. Thank You :)

**Comment by Dilip-Jain** [comment]
Please assign this to me. Thank You :)

**Comment by namrata18s** [comment]
Could you assign this task yo me?
