### ISSUE TITLE
Fibonacci search | java

### ISSUE THREAD

**Issue by shreyasd302** [div-bargali/Data-Structures-and-Algorithms#703]
## **`Title`** - Fibonacci search

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by shreyasd302** [comment]
Can I work on this please?

**Comment by elizabethqiu** [comment]
I'd like to help out with this!
