### ISSUE TITLE
Single Linked List | C++

### ISSUE THREAD

**Issue by davbrito** [div-bargali/Data-Structures-and-Algorithms#706]
## Enhance Single Linked List, C++

The data structure will be made generic so the data could be any type.
It will be crafted using OOP.

### Type of Issue -

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [x] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by davbrito** [comment]
Please assign this issue to me

**Comment by sbindal057** [comment]
please assign this issue to me. I'll do it in c++
