### ISSUE TITLE
trivial hashing in C++

### ISSUE THREAD

**Issue by KhushiGangopadhyay** [div-bargali/Data-Structures-and-Algorithms#707]
Trivial hashing 

### Type of Issue -

Please add/delete options that are not relevant.

- Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
-  C++
- [ ] Java
- [ ] C
- [ ] Go
- [ ] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by KhushiGangopadhyay** [comment]
please assign this to me

**Comment by sawyer1997** [comment]
I would like to try, please assign.

**Comment by nibbithecoder** [comment]
please assign this task to me .

**Comment by KhushiGangopadhyay** [comment]
Hello @div-bargali, I have forked the repo and then i tried cloning but I am getting this error:

Cloning into 'Data-Structures-and-Algorithms'...
remote: Enumerating objects: 3899, done.
remote: Total 3899 (delta 0), reused 0 (delta 0), pack-reused 3899           bjects:  97% (3783/3899), 19.89 MiB | 4.36 MiB/s
Receiving objects: 100% (3899/3899), 20.27 MiB | 4.37 MiB/s, done.
Resolving deltas: 100% (1513/1513), done.
error: invalid path 'C++/Algorithms/Graph-Algorithms/A*_Search_Algorithm.cpp'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/' 

only a empty folder of the forked repo is getting cloned, Can you help me out to solve this please

**Comment by div-bargali** [comment]
@KhushiGangopadhyay It's naming error, will be fixed soon.

**Comment by div-bargali** [comment]
Try cloning the repo again.

**Comment by KhushiGangopadhyay** [comment]
@div-bargali I tried again but it shows the same error :(

**Comment by div-bargali** [comment]
@KhushiGangopadhyay You will have to delete your forked repo, and fork this repo again.

**Comment by KhushiGangopadhyay** [comment]
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'C++/Data-Structures/LinkedList/OrderedLinkedListStrings.cpp'
  'C++/Data-Structures/LinkedList/OrderedLinkedlistStrings.cpp'


got this error now :(

**Comment by div-bargali** [comment]
@KhushiGangopadhyay Can you please try it once more? Delete the forked repo from github, then fork it again.

**Comment by KhushiGangopadhyay** [comment]
Done!!! :)
