### ISSUE TITLE
Sorting Algorithms in C

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#71]
Implement various sorting algorithms in C. 

### **Steps to contribute -**
1. Open a new issue stating the algorithm you want to implement.
2. Create a new PR and reference the issue in that PR.
3. Wait for the PR to be merged 🎉.

**Comment by adata111** [comment]
I'd like to do merge sort and selection sort

**Comment by SusnatoPrime007** [comment]
I'd be doing the quick sort.

**Comment by shevya06** [comment]
I'd like to do insertion sort

**Comment by Krishna-Sivakumar** [comment]
I can do the merge sort.

**Comment by sayan2044** [comment]
i will do the radix sort

**Comment by sayan2044** [comment]
> i will do the radix sort

radix sort done

**Comment by SusnatoPrime007** [comment]
I'd like to do the heap sort.

**Comment by code-netizen** [comment]
i will do topological sort

**Comment by div-bargali** [comment]
Resolved in #76 #107 #102 #81 #80 and #75 .
Open new issues for adding more sorting algorithms.
