### ISSUE TITLE
A* Search Algorithm | C++

### ISSUE THREAD

**Issue by davbrito** [div-bargali/Data-Structures-and-Algorithms#733]
## Rename A* Search Algorithm File -

The filename of https://github.com/div-bargali/Data-Structures-and-Algorithms/blob/main/C%2B%2B/Algorithms/Graph-Algorithms/A*_Search_Algorithm.cpp is causing problems on Windows when making pull with Git because of the `*` on its name.

### Type of Issue -

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [x] Bug Fix

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by davbrito** [comment]
It could be renamed as A-Star Search Algorithm

**Comment by davbrito** [comment]
Assign it to me

**Comment by div-bargali** [comment]
@davbrito  Thank you for bringing it to our attention. It has been fixed now.
