### ISSUE TITLE
Inversions Count | C++

### ISSUE THREAD

**Issue by swathi-vennela** [div-bargali/Data-Structures-and-Algorithms#741]
## **`Finding inversions count in an array | C++`** -

**what will change** - Add a solution to find Inversions count in an array in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] C
- [x] Go
- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by rachitmanas** [comment]
Can I also work on this?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me
