### ISSUE TITLE
Stack implementation using Doubly Linked Lists | C

### ISSUE THREAD

**Issue by hemanth-kotagiri** [div-bargali/Data-Structures-and-Algorithms#742]
### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by hemanth-kotagiri** [comment]
I would like to be assigned for this. I already have the worked out the code, and I will immediately raise the PR. Thanks!

**Comment by hemanth-kotagiri** [comment]
@div-bargali Can you please assign me this issue, I forgot to add myself as an assignee. I already have the commit read to be raised as a PR. If you could add me, I will immediately raise the PR. Thanks, man!

**Comment by Shreyas-Gupta-21** [comment]
Interested to work on this.

**Comment by hemanth-kotagiri** [comment]
@Shreyas-Gupta-21 I have already worked on it and I've raised a PR as well. Here's my PR: #749
