### ISSUE TITLE
Linear Search | C#

### ISSUE THREAD

**Issue by peaky76** [div-bargali/Data-Structures-and-Algorithms#743]
## **Linear Search** -

A linear search algorithm for C#

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C#

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by peaky76** [comment]
I'd like to work on this please as I'm teaching myself C#

**Comment by Shreyas-Gupta-21** [comment]
Interested to work on this.

**Comment by Nitish-web-nik** [comment]
I want to contribute to this issue, Please assign this to me.
