### ISSUE TITLE
Insertion Sort | Haskell

### ISSUE THREAD

**Issue by anbclausen** [div-bargali/Data-Structures-and-Algorithms#746]
## Insertion Sort in Haskell

I will add an insertion sort algorithm, implemented in Haskell.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by anbclausen** [comment]
Please assign this issue to me. :)

**Comment by Nitish-web-nik** [comment]
I want to contribute to this issue, Please assign this to me.
