### ISSUE TITLE
Implement Queue using Two Stacks | Java

### ISSUE THREAD

**Issue by Tascate** [div-bargali/Data-Structures-and-Algorithms#747]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Tascate** [comment]
Please assign this issue to me! :)

**Comment by swathi-vennela** [comment]
Please assign me for the C++ version of this issue
