### ISSUE TITLE
Fibonacci numbers | C++

### ISSUE THREAD

**Issue by Apoorva-Datir** [div-bargali/Data-Structures-and-Algorithms#752]
## **`Title`** -  Fibonacci numbers

**what will change** - This program prints nth fibonacci number when a number n is given.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Apoorva-Datir** [comment]
Can i work on this?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm interested to contribute in this .

**Comment by Nitish-web-nik** [comment]
Please assign this issue to me.

**Comment by Nitish-web-nik** [comment]
Please assign this issue to me @div-bargali .

**Comment by Helanmariyam** [comment]
am interested to contribute

**Comment by Oratoccio** [comment]
Hello I'm interested to contribute.

**Comment by sourabhjain9887** [comment]
I want to contribute , assign this issue to me.

**Comment by gaurisharma360** [comment]
Can you please assign me this issue in c, python, or java?
