### ISSUE TITLE
Pascal's triangle | Python

### ISSUE THREAD

**Issue by Apoorva-Datir** [div-bargali/Data-Structures-and-Algorithms#753]
## **`Title`** - Pascal's triangle

**what will change** - This program takes an integer value n as input and prints first n lines of the Pascal’s triangle.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by Apoorva-Datir** [comment]
Can I work on this issue?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm interested to contribute in this .

**Comment by Nitish-web-nik** [comment]
I want to contribute to this issue, please assign it to me @div-bargali .
