### ISSUE TITLE
Stack | C++

### ISSUE THREAD

**Issue by davbrito** [div-bargali/Data-Structures-and-Algorithms#756]
## Implement Stack

Implement a stack data structure in https://github.com/div-bargali/Data-Structures-and-Algorithms/blob/main/C%2B%2B/Data-Structures/Stack/Stack.cpp . Because at this moment it just uses `std::stack`

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by davbrito** [comment]
Assign this to me please

**Comment by Nitish-web-nik** [comment]
**I want to contribute to this issue, Please assign this to me @div-bargali**
