### ISSUE TITLE
Fibonacci Numbers | Go

### ISSUE THREAD

**Issue by brisingr24** [div-bargali/Data-Structures-and-Algorithms#771]
## **`Title`** - Fibonacci numbers

**what will change** -  This program prints nth fibonacci number when a number n is given.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Go

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by brisingr24** [comment]
Please assign this issue to me

**Comment by geekyvyas** [comment]
Please assign this issue to me
