### ISSUE TITLE
Competitive coding problems.

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Data-Structures-and-Algorithms#78]
### Would you guys like to implement solutions of famous coding problems? 🤔 
If yes, let me know! 👍

**Comment by jai2dev** [comment]
Yes

**Comment by p-nath** [comment]
Yeah, that would be great!

**Comment by RamneekKaur983** [comment]
Yess!!!

**Comment by jai2dev** [comment]
@div-bargali update ?

**Comment by div-bargali** [comment]
@jai2dev I'll let you guys know by tomorrow. 🕥

**Comment by Rsr0** [comment]
Yeah sure

**Comment by ShahrozTanveer** [comment]
Yes!

**Comment by div-bargali** [comment]
Guys, so if I allow solutions for coding problems, I'd need maintainers for this repo as it would be hectic for me to manage it. So is any one of you interested? 🤔

**Comment by jai2dev** [comment]
@div-bargali okay i am in.

**Comment by RajdeepDey010** [comment]
I ave got some competitive problems. I would love to add those.

**Comment by div-bargali** [comment]
> Guys, so if I allow solutions for coding problems, I'd need maintainers for this repo as it would be hectic for me to manage it. So is any one of you interested? 🤔

Check README.md. ✉️

**Comment by atish-90** [comment]
can i add some important competitive questions along with their solutions of different data structure like kadane's algorithm,etc?

**Comment by atish-90** [comment]
i would like to work upon this issue

**Comment by sbm1arora** [comment]
yes!!

**Comment by harshulab** [comment]
yes!
