### ISSUE TITLE
Bubble sort | C#

### ISSUE THREAD

**Issue by joll05** [div-bargali/Data-Structures-and-Algorithms#784]
## **`Bubble sort`** -

**what will change** - Bubble sort will be added as a sorting algorithm in C#.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C#

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by joll05** [comment]
Could you assign me to this issue, please?

**Comment by vaibhav1865** [comment]
Hello there,
Please assign this to me
