### ISSUE TITLE
Kth Missing Positive Number | C++

### ISSUE THREAD

**Issue by Anish0203** [div-bargali/Data-Structures-and-Algorithms#787]
## **`Kth Missing Positive Number`** -

**what will change** -
This program will find the Kth missing positive number in an array sorted in a strictly increasing order.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by Anish0203** [comment]
Please assign this issue to me.

**Comment by vaibhav1865** [comment]
Hello there,
Please assign this to me
