### ISSUE TITLE
Remove duplicates from sorted array | C++

### ISSUE THREAD

**Issue by Anish0203** [div-bargali/Data-Structures-and-Algorithms#789]
## **`Remove duplicates from sorted array`** -

**what will change** -
This program will remove duplicates from the sorted array with O(1) extra memory.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by Anish0203** [comment]
Please assign this issue to me.

**Comment by vaibhav1865** [comment]
Greetings there, please assign this to me

**Comment by sawyer1997** [comment]
Can work on Python for this one.
