### ISSUE TITLE
Searching Algorithms in Python; like Linear search, Binary search and Jump search

### ISSUE THREAD

**Issue by jai2dev** [div-bargali/Data-Structures-and-Algorithms#79]

**Comment by suprimnakarmi** [comment]
Can you please assign this to me too?

**Comment by jai2dev** [comment]
@suprimnakarmi I will be doing linear search binary search and Jump search, If you find any other algorithms then mention it.

**Comment by suprimnakarmi** [comment]
Okay, @jai2dev. Can I do interpolation search and exponential search?

**Comment by SusnatoPrime007** [comment]
Can I do the fibonacci search in Java or Python?

**Comment by div-bargali** [comment]
@suprimnakarmi @SusnatoPrime007 Open new issues guys. Make sure its not already implemented or suggested in any issue.

**Comment by SusnatoPrime007** [comment]
> @suprimnakarmi @SusnatoPrime007 Open new issues guys. Make sure its not already implemented or suggested in any issue.

Can I also do the bubble sort in Java?
