### ISSUE TITLE
Adding Factorial Equation  | C++

### ISSUE THREAD

**Issue by mamadou-diallo** [div-bargali/Data-Structures-and-Algorithms#790]
## **`Adding Factorial Equation`** -

**Factorial function will be written iteratively and recursively** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by mamadou-diallo** [comment]
I will be taking care of this issue !

**Comment by farFromShallow101** [comment]
Hello there. Can I contribute to this issue? I am totally new to open source.

**Comment by mamadou-diallo** [comment]
Hello @farFromShallow101 I see that you've commented on two of my issues, in the spirit of hacktoberfest please feel free to take this care of this issue.  And I will take care of Issue #791  
@div-bargali - Please assign this to @farFromShallow101 ! Thank you !

**Comment by div-bargali** [comment]
Assigned to @farFromShallow101
