### ISSUE TITLE
Adding Power Equation | C++

### ISSUE THREAD

**Issue by mamadou-diallo** [div-bargali/Data-Structures-and-Algorithms#791]
## **`Adding Power Equation`** -

**Power function will be written iteratively and recursively** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by mamadou-diallo** [comment]
I will take care of this issue !

**Comment by sawyer1997** [comment]
Would like to do in 2-3 different languages, Python, C++, Golang.

**Comment by farFromShallow101** [comment]
Hi, I really want to take this issue as I am a total newbie in open source. I will contribute in C++ language.

**Comment by mamadou-diallo** [comment]
@sawyer1997 I am already taking of this in C++ but I am sure @divyakantyadav wouldn't be against other languages, I suggest that you create an issue for those languages so that they can properly be assigned to you.

**Comment by mamadou-diallo** [comment]
@divyakantyadav This issue has been fixed  with PR #807 :)
