### ISSUE TITLE
Median of an array in O(N) | C++

### ISSUE THREAD

**Issue by rachitmanas** [div-bargali/Data-Structures-and-Algorithms#792]
## **`Adding C++ code to find median of an array in O(N) using Median of Medians Algorithm`** -

**A program to get Median of an array with n elements in O(N) runtime will be added** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by rachitmanas** [comment]
I would like to work on this issue!

**Comment by sawyer1997** [comment]
Hi, would like to do, let me know if I can be assigned.

**Comment by rachitmanas** [comment]
I have made the PR @div-bargali .
