### ISSUE TITLE
Binary search | Swift

### ISSUE THREAD

**Issue by Faaatman** [div-bargali/Data-Structures-and-Algorithms#815]
## **`Binary search in Swift`**

**what will change** -
Create a new folder in swift called algorithms and add binary search file in it.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Other language
- [x] Swift

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by Anurag-ak99** [comment]
need to WAP of binary search in swift?If this is the issue then please can you assign it to me?

**Comment by Faaatman** [comment]
> need to WAP of binary search in swift?If this is the issue then please can you assign it to me?

I have created this issue so that it gets assigned to me and I add the code. Sorry.
