### ISSUE TITLE
Delete by index i linked list | Go

### ISSUE THREAD

**Issue by Matheus73** [div-bargali/Data-Structures-and-Algorithms#826]
## **`Title`** -

**what will change** -

* I will implement a delete by index in linked list

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Go

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by Matheus73** [comment]
@div-bargali Please man, assing to me

**Comment by Debadri3** [comment]
Assign this to me please

**Comment by skabdurrahamanhossain** [comment]
Assign this to me

**Comment by deepanshuoct12** [comment]
assign this to me please
