### ISSUE TITLE
Pair With Given Difference | C++

### ISSUE THREAD

**Issue by 0ChanAk** [div-bargali/Data-Structures-and-Algorithms#834]
## **`Title`** -Pair With Given Difference

**what will change** - Add algorithm in C++ to the given problem.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by 0ChanAk** [comment]
@div-bargali please assign this issue to me. Thanks.

**Comment by akshaychaudhari** [comment]
Please assign the issue to me.

**Comment by hemanth-kotagiri** [comment]
Sorry, @akshaychaudhari. The one who raised the Issue will have the highest priority. Please come up with a new issue for any new implementations that do not yet exist in this repository so that I can assign you there.

Thanks!
