### ISSUE TITLE
Error in permutation of string and Add comments and performance analysis to data structure folder and algorithm folder in C++ folder, respectively | C++

### ISSUE THREAD

**Issue by ji-sang-geun** [div-bargali/Data-Structures-and-Algorithms#864]
## **`Title`** -
Error in permutation of string and  Add comments and performance analysis to data structure folder and algorithm folder in C++ folder, respectively
**what will change** -

First, we have finished translating Readme file, Code of Conduct file, Contributing file into korean.

The next thing we want to contribute is to add comments and performance analysis to the data structures folder and algorithms folder inside the C++ folder, respectively.
In the case of comments, we'll add them within the code, and we're almost done with this now.
Next, in the case of performance analysis, as mentioned before, only the title is written in the Readme file that exists in the data structure and algorithm section, and I found out that there is a file without content.
I will add algorithm description and performance analysis to that section.

(For example)
ex) C++/Algorithms/Backtracking/readme.md
### Backtracking-Algorithms ###
1. CROSSWARD.cpp
=> Using Crossward Algorithm, user inputs 10 words 
Time Complexity: ____
Space Complexity: ____

2. Premutation of string.cpp
Permutation of string is a algorithm that functions to find all possible permutations of a given string, for example if there are given string "ABC" then ABC,ACB,BAC,BCA,CBA,CAB is the result    also there are some error in code we need to delete void permutations(string str, int i, int n,int j, int k ) -> void permutations(string str, int i, int n ) 
Time Complexity: ____
Space Complexity: ____
….

Second, while looking at the code, we found an error in the permutations function in the [C++/Algorithms/Backtracking/Permutation_of_string.cpp] file.
The current function is:
![image](https://user-images.githubusercontent.com/66692986/99096831-1e0b6300-261a-11eb-9bfb-5e9f508b9cf6.png)
As you can see in the picture, I confirmed that int j and int k are the wrong parameters. 
![image](https://user-images.githubusercontent.com/66692986/99096916-39766e00-261a-11eb-8740-95c7b477f5c1.png)
we suggest modifying it as follows.

### Type of Issue -

Please add/delete options that are not relevant.

- [] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] C
- [] Go
- [] Other language

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by M2kishore** [comment]
I would like to give a try. can I?
