### ISSUE TITLE
Adding Square Root Equation | C++

### ISSUE THREAD

**Issue by mamadou-diallo** [div-bargali/Data-Structures-and-Algorithms#865]
Square Root function will be written iteratively and recursively -

Type of Issue -
Please add/delete options that are not relevant.

 Adding New Code
Programming Language
Please add/delete options that are not relevant.

 C++
Self Check
Ask for issue assignment before making Pull Request.
Add your file in the proper folder
Clean Code and Documentation for better readability
Add Title and Description of the program in the file
🌟 Star it 🍴Fork it 🤝 Contribute to it!

Happy Coding!

**Comment by hemanth-kotagiri** [comment]
@sharmishtha2401 you can proceed to work on this issue.
