### ISSUE TITLE
Maximum and minimum of an array using minimum number of comparisons | C++

### ISSUE THREAD

**Issue by akrish4** [div-bargali/Data-Structures-and-Algorithms#871]
## **Maximum and minimum of an array using minimum number of comparisons** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by akrish4** [comment]
I would like to work on this issue , Kindly assign me this issue.

**Comment by anishsingh935** [comment]
Hi I want to solve this issue .kindly assign me

**Comment by swap54** [comment]
Hello, I would like to work on this issue, kindly assign me.
