### ISSUE TITLE
Add Kmeans and CNN algos (Python)

### ISSUE THREAD

**Issue by Anjali001** [div-bargali/Data-Structures-and-Algorithms#88]
Hello.
I wish to contribute by adding Kmeans clustering algorithm and Convolutional Neural Network Algo  in Python. Can I proceed with that? If yes , please add the hacktober label to this issue.
Also, should I contribute in .py or .ipynb ?

**Comment by div-bargali** [comment]
Hi @Anjali001. Sure, you can go ahead 👍 
If it's possible, contribute in .py, but Jupyter Notebook is aceepted as well.
