### ISSUE TITLE
Longest Common Subsequence | C

### ISSUE THREAD

**Issue by Anurag-Nayak** [div-bargali/Data-Structures-and-Algorithms#886]
## **`Longest Common Subsequence`** -

**Want to add the algorithm to this problem under the DP folder in Algorithm** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by EANimesha** [comment]
I like to contribute assign me

**Comment by shatanshu123** [comment]
I would like to contribute
