### ISSUE TITLE
Subarrays With Sum Zero | C++

### ISSUE THREAD

**Issue by dishagupta2413** [div-bargali/Data-Structures-and-Algorithms#887]
## **` Subarrays With Sum Zero`** -

**want to add this problem in arrays maps are also used in this problem will be a good problem to add** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by Sun-0321** [comment]
@dishagupta2413   Can you please assign this task to me ?
I will do it in C++.

**Comment by Sreetama2001** [comment]
@dishagupta2413  Is it ok if I code it? I will do it C++

**Comment by Sun-0321** [comment]
Can I ? @dishagupta2413 
I asked first.

**Comment by hemanth-kotagiri** [comment]
Hello, @Sun-0321. Yes, I will assign this issue to you. But, if you fail to produce a PR within the stipulated time, I will assign it to @Sreetama2001.

**Comment by Sun-0321** [comment]
> 
> 
> Hello, @Sun-0321. Yes, I will assign this issue to you. But, if you fail to produce a PR within the stipulated time, I will assign it to @Sreetama2001. Also, note that the author of this issue obtains the highest priority with regards to the implementation. Therefore, you can always create your own issues and raise PRs if this issue has already been addressed.

Ok. Thank You ! I will upload in 10 mins.

**Comment by Udyansingh** [comment]
Can you please assign this task to me.
