### ISSUE TITLE
Stack using Queues | C

### ISSUE THREAD

**Issue by Aron-R** [div-bargali/Data-Structures-and-Algorithms#902]
## **`Stack using Queues`** 

**what will change** - 
I’d like to add a stack implementation using queues in C language under data structures. 

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] C

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by coder284** [comment]
@Aron-R can you please assign it to me ?

**Comment by Aron-R** [comment]
> @Aron-R can you please assign it to me ?

I don’t think I can assign this to anyone, The CONTRIBUTIONS.md file said that if I thought something is missing, I can create an issue and so I’ve created an issue and if they happen to assign it to me I would work on it

**Comment by Aron-R** [comment]
Hey @div-bargali 
I’ve added the code for this
Check it out ❤️
