### ISSUE TITLE
Data Structure | Linked List | Cpp

### ISSUE THREAD

**Issue by Ambareen09** [div-bargali/Data-Structures-and-Algorithms#903]
## **`Merge two sorted linked lists`** -

**Will add a file for the code** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding!

**Comment by lucy2512** [comment]
I would like to work on it.
Will you please assign it to me?

**Comment by BharaniSri10** [comment]
can i do it in c++?

**Comment by LikhithaTadikonda** [comment]
Please assign this to me I would like to contribute ASAP! :)
