### ISSUE TITLE
I'd be doing the quick sort.

### ISSUE THREAD

**Issue by SusnatoPrime007** [div-bargali/Data-Structures-and-Algorithms#95]
I'd be doing the quick sort.

_Originally posted by @SusnatoPrime007 in https://github.com/div-bargali/Data-Structures-and-Algorithms/issues/71#issuecomment-704852818_

**Comment by div-bargali** [comment]
Up for grab! 🎫

**Comment by SusnatoPrime007** [comment]
Please assign me,I got confused between so many issues, I'd like to contribute in this

**Comment by div-bargali** [comment]
@SusnatoPrime007 Assigned.
