### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by shevya06** [div-bargali/Data-Structures-and-Algorithms#96]
I'd like to do searching in a rotated sorted array using binary search.

**Comment by div-bargali** [comment]
@shevya06 Mention the language you'll use.

**Comment by shevya06** [comment]
java

**Comment by div-bargali** [comment]
Assigned to @shevya06 . Make sure your implementaion is under `Java/Algorithms/Searching/BinarySearch`

**Comment by SusnatoPrime007** [comment]
I'd like to do the basic binary search program in C.

**Comment by div-bargali** [comment]
@SusnatoPrime007 Open a new issue please.

**Comment by SusnatoPrime007** [comment]
I'd like to do the binary search tree in Java.Please assign me to this.

**Comment by rishier827** [comment]
I'd like to do the binary search tree in python3.Please assign me to this.

**Comment by ambuj2000** [comment]
Please assign me this issue

**Comment by Shreya2221** [comment]
I would like to do binary search in Java .Please assign me to this.

**Comment by SnehhaPadmanabhan** [comment]
I would like to do "Finding the index of first/last occurrence of an element in a sorted array" using binary search in C++.

**Comment by div-bargali** [comment]
Up for grabs!

**Comment by mavneeK** [comment]
i would like to contribute to this
