### ISSUE TITLE
Red-Black Search Trees (Python)

### ISSUE THREAD

**Issue by Krishna-Sivakumar** [div-bargali/Data-Structures-and-Algorithms#98]
I'd like to implement red-black trees in python for this collection. 
Any suggestions? @div-bargali

**Comment by div-bargali** [comment]
Up for grabs!

**Comment by Krishna-Sivakumar** [comment]
I'm done with the code, can I claim this again? @div-bargali

**Comment by Sumit2399** [comment]
This is seems interesting can I work on it.

**Comment by Sumit2399** [comment]
Hoping for merge soon.

**Comment by Sumit2399** [comment]
Thanks @div-bargali for the merge.Looking forward to more contributions in the future.
